post:
    servicePointUuids:
        - Count:
              min: 1
    serviceTypeUuid:
        - NotBlank: ~
    productOfferServicePointAvailabilityRequestItems:
        - All:
              constraints:
                  - Collection:
                        allowExtraFields: true
                        fields:
                            productConcreteSku:
                                - NotBlank: ~
                            quantity:
                                - NotNull: ~
                                - GreaterThanOrEqual:
                                      value: 0
